begin;

insert into public.projects (
  slug,
  name,
  headline,
  summary,
  description,
  whatsapp_phone,
  status,
  sort_order,
  is_featured,
  approximate_location_text,
  published_at
)
values
  (
    'aurelian-coast',
    'Aurelian Coast',
    'Signature Villas',
    'Colección frente al mar con foco en hospitalidad, privacidad y lectura arquitectónica sobria.',
    'Proyecto costero orientado a residencias de alta gama con una narrativa visual silenciosa y premium.',
    '+18095550101',
    'published',
    10,
    true,
    'Cap Cana, República Dominicana',
    timezone('utc', now())
  ),
  (
    'azure-enclave',
    'Azure Enclave',
    'Curated Lots',
    'Lotes de baja densidad para clientes que priorizan paisaje, calma y ejecución contemporánea.',
    'Desarrollo pensado para construir con ritmo controlado, acceso rápido a playa y una lectura natural del terreno.',
    '+18095550102',
    'published',
    20,
    true,
    'Las Terrenas, Samaná',
    timezone('utc', now())
  ),
  (
    'costa-reserva',
    'Costa Reserva',
    'Family Retreats',
    'Residencias cálidas para operación familiar, renta selectiva y uso extendido durante todo el año.',
    'Inventario residencial con un tono menos ostentoso y más habitable, pensado para familias internacionales.',
    '+18095550103',
    'published',
    30,
    false,
    'Punta Cana Village',
    timezone('utc', now())
  )
on conflict (slug) do update
set
  name = excluded.name,
  headline = excluded.headline,
  summary = excluded.summary,
  description = excluded.description,
  whatsapp_phone = excluded.whatsapp_phone,
  status = excluded.status,
  sort_order = excluded.sort_order,
  is_featured = excluded.is_featured,
  approximate_location_text = excluded.approximate_location_text,
  published_at = excluded.published_at;

insert into public.properties (
  project_id,
  property_type_id,
  slug,
  title,
  summary,
  description,
  listing_mode,
  commercial_status,
  price_mode,
  base_currency,
  price_amount,
  bedrooms,
  bathrooms,
  parking_spaces,
  construction_area_m2,
  lot_area_m2,
  approximate_location_text,
  whatsapp_phone,
  is_featured,
  published_at
)
values
  (
    (select id from public.projects where slug = 'aurelian-coast'),
    (select id from public.property_types where slug = 'villa'),
    'obsidian-sanctuary',
    'The Obsidian Sanctuary',
    'Villa de líneas serenas, patio acuático y secuencia espacial pensada para hospitalidad de alto nivel.',
    'Diseñada como refugio editorial frente al mar, combina piedra cálida, madera oscura y aperturas controladas para una experiencia silenciosa y premium.',
    'sale',
    'available',
    'fixed',
    'USD',
    2950000,
    5,
    5,
    4,
    620,
    1900,
    'Cap Cana, República Dominicana',
    '+18095550101',
    true,
    timezone('utc', now())
  ),
  (
    (select id from public.projects where slug = 'azure-enclave'),
    (select id from public.property_types where slug = 'lot'),
    'azure-enclave-lot-7',
    'The Azure Enclave Lot 7',
    'Lote premium para residencia de baja densidad con visuales limpias y acceso rápido a playa y club.',
    'Una pieza pensada para quien quiere construir con ritmo lento y lenguaje contemporáneo, sin perder cercanía con la costa.',
    'sale',
    'available',
    'fixed',
    'USD',
    540000,
    null,
    null,
    null,
    null,
    2400,
    'Las Terrenas, Samaná',
    '+18095550102',
    true,
    timezone('utc', now())
  ),
  (
    (select id from public.projects where slug = 'costa-reserva'),
    (select id from public.property_types where slug = 'villa'),
    'terracotta-house',
    'Terracotta House',
    'Residencia cálida con circulación abierta, comedor exterior y un lenguaje más doméstico, menos ostentoso.',
    'La propuesta apunta a familias que valoran privacidad, textura material y una atmósfera relajada con excelente operatividad.',
    'sale_rent',
    'reserved',
    'on_request',
    'USD',
    null,
    4,
    4,
    2,
    480,
    null,
    'Punta Cana Village',
    '+18095550103',
    false,
    timezone('utc', now())
  )
on conflict (slug) do update
set
  project_id = excluded.project_id,
  property_type_id = excluded.property_type_id,
  title = excluded.title,
  summary = excluded.summary,
  description = excluded.description,
  listing_mode = excluded.listing_mode,
  commercial_status = excluded.commercial_status,
  price_mode = excluded.price_mode,
  base_currency = excluded.base_currency,
  price_amount = excluded.price_amount,
  bedrooms = excluded.bedrooms,
  bathrooms = excluded.bathrooms,
  parking_spaces = excluded.parking_spaces,
  construction_area_m2 = excluded.construction_area_m2,
  lot_area_m2 = excluded.lot_area_m2,
  approximate_location_text = excluded.approximate_location_text,
  whatsapp_phone = excluded.whatsapp_phone,
  is_featured = excluded.is_featured,
  published_at = excluded.published_at;

commit;
